[package]
name = "neols"
version = "0.0.2"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
